version: '3'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ../utils:/opt/airflow/utils
    - ../dags:/opt/airflow/dags
    - ../logs:/opt/airflow/logs
    - ../resources:/opt/airflow/resources
  depends_on:
    - postgres
  networks:
    - local_ps_af

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - local_ps_af

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname test --lastname test --role Admin --email admin@gmail.com --password admin && airflow scheduler"

networks:
  local_ps_af: